/**
 * Copyright (c) 2012-2014 Microsoft Mobile.
 */

var CONTROL_OPACITY = 1.0;

var SETTINGS_LABEL_WIDTH = 145;
var SETTINGS_SLIDER_WIDTH = 380;
var SETTINGS_LABEL_PANEL_OPACITY = 0.90;

var SETTINGS_VERTICAL_SPACING = 13;

var BUTTON_ROW_BUTTON_WIDTH = 57;
var BUTTON_ROW_BUTTON_HEIGHT = 50;
var BUTTON_ROW_BUTTON_TEXT_WIDTH = SETTINGS_SLIDER_WIDTH / 2;
